name=esp32-afsk
version=0.1.1
author=Dmitry Kaukov
maintainer=Dmitry Kaukov
sentence=ESP32 AFSK modem helper library.
paragraph=Modulates and demodulates AFSK audio for AX.25 packet radio applications on ESP32-class microcontrollers.
category=Communication
url=https://github.com/dkaukov/esp32-afsk
architectures=esp32
includes=AfskDemodulator.h,AfskModulator.h
